[options]
admin_passwd = $pbkdf2-sha512$600000$OgeA8J4TojSG0Np7j1HqHQ$saohnXnIwBZCVXlpNnXg4P/rrdJ7hykdMw1YFy1vWPA8JqDqH6cpHuqTueX8uYX/WJ3VJM2VpNeMR6zSXTR5xA
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
addons_path = /mnt/extra-addons
list_db = True
